"""add catalog tables

Revision ID: 72044d02df45
Revises: f9a8b7c6d5e4
Create Date: 2026-09-18 00:25:27.027598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72044d02df45'
down_revision: Union[str, Sequence[str], None] = 'f9a8b7c6d5e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('customer_notes_store_id_fkey'), 'customer_notes', type_='foreignkey')
    op.drop_column('customer_notes', 'store_id')
    op.drop_column('customer_notes', 'created_by_staff_id')
    op.drop_column('customers', 'version')
    op.drop_column('customers', 'note')
    op.drop_column('customers', 'tags')
    op.alter_column('permissions', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=False)
    op.create_unique_constraint('uq_permissions_code', 'permissions', ['code'])
    op.drop_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', type_='unique')
    op.create_unique_constraint('uq_refresh_tokens_hash', 'refresh_tokens', ['token_hash'])
    op.alter_column('sales_channels', 'channel_id',
               existing_type=sa.UUID(),
               comment='Channel id.',
               existing_comment='UUID PK generated in Python.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'store_id',
               existing_type=sa.UUID(),
               comment='Owning store.',
               existing_comment='FK → stores.store_id.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Online Store, Admin Draft, Instagram, etc.',
               existing_comment='Human-readable channel label.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=32),
               comment='STOREFRONT, ADMIN, MARKETPLACE, POS, API.',
               existing_comment="Channel type: 'online_store' | 'pos' | 'api'.",
               existing_nullable=False)
    op.alter_column('sales_channels', 'status',
               existing_type=sa.VARCHAR(length=24),
               comment='ACTIVE/INACTIVE.',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('sales_channels', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Channel-specific configuration.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sales_channels', 'version',
               existing_type=sa.BIGINT(),
               comment='Optimistic concurrency version for admin edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('sales_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Created time.',
               existing_comment='UTC timestamp of first INSERT (immutable).',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_sales_channels_type'), table_name='sales_channels')
    op.drop_constraint(op.f('uq_sales_channels_store_name'), 'sales_channels', type_='unique')
    op.drop_constraint(op.f('staff_members_user_id_key'), 'staff_members', type_='unique')
    op.create_unique_constraint('uq_staff_members_store_user', 'staff_members', ['store_id', 'user_id'])
    op.alter_column('store_settings', 'settings_id',
               existing_type=sa.UUID(),
               comment='Settings row id.',
               existing_comment='UUID PK generated in Python.',
               existing_nullable=False)
    op.alter_column('store_settings', 'store_id',
               existing_type=sa.UUID(),
               comment='One settings row per store.',
               existing_comment='FK → stores.store_id (1-to-1).',
               existing_nullable=False)
    op.alter_column('store_settings', 'order_prefix',
               existing_type=sa.VARCHAR(length=20),
               comment='Human order number prefix.',
               existing_comment='Prefix for human-readable order numbers.',
               existing_nullable=False,
               existing_server_default=sa.text("'ORD'::character varying"))
    op.alter_column('store_settings', 'weight_unit',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=8),
               comment='kg, g, lb.',
               existing_comment="Weight unit: 'kg' or 'lb'.",
               existing_nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('store_settings', 'dimension_unit',
               existing_type=sa.VARCHAR(length=8),
               comment='cm, in.',
               existing_nullable=False,
               existing_server_default=sa.text("'cm'::character varying"))
    op.alter_column('store_settings', 'tax_inclusive',
               existing_type=sa.BOOLEAN(),
               comment='Whether catalog price already contains tax.',
               existing_comment='Whether product prices include tax.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('store_settings', 'allow_guest_checkout',
               existing_type=sa.BOOLEAN(),
               comment='Guest checkout switch.',
               existing_comment='Whether shoppers may checkout without an account.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('store_settings', 'inventory_policy',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=24),
               comment='Release 1 supports DENY only.',
               existing_comment="'deny' stops sale when OOS; 'continue' allows overselling.",
               existing_nullable=False,
               existing_server_default=sa.text("'DENY'::character varying"))
    op.alter_column('store_settings', 'checkout_expiry_minutes',
               existing_type=sa.INTEGER(),
               comment='Reservation/checkout lifetime.',
               existing_comment='Minutes before an open checkout session expires.',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('store_settings', 'version',
               existing_type=sa.BIGINT(),
               comment='Optimistic concurrency version for settings edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('store_settings', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Low-risk extensible flags.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('store_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'store_id',
               existing_type=sa.UUID(),
               comment='Primary store identifier.',
               existing_comment='UUID PK generated in Python before INSERT.',
               existing_nullable=False)
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=160),
               comment='Merchant/store display name.',
               existing_comment='Human-readable display name.',
               existing_nullable=False)
    op.alter_column('stores', 'legal_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Registered business name.',
               existing_comment='Registered legal business name.',
               existing_nullable=True)
    op.alter_column('stores', 'default_currency',
               existing_type=sa.CHAR(length=3),
               comment='ISO currency such as INR.',
               existing_comment='ISO 4217 currency code.',
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('stores', 'country_code',
               existing_type=sa.CHAR(length=2),
               comment='Primary ISO country code.',
               existing_comment='ISO 3166-1 alpha-2 country code.',
               existing_nullable=False)
    op.alter_column('stores', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               comment='Store operating timezone.',
               existing_comment='IANA timezone identifier.',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('stores', 'status',
               existing_type=sa.VARCHAR(length=24),
               comment='ACTIVE, PAUSED, CLOSED.',
               existing_comment='StoreStatus: active | suspended | pending_setup.',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('stores', 'version',
               existing_type=sa.BIGINT(),
               comment='Optimistic concurrency version for admin edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Creation time UTC.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last update UTC.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.alter_column('stores', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last update UTC.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Creation time UTC.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('stores', 'version',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Optimistic concurrency version for admin edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('stores', 'status',
               existing_type=sa.VARCHAR(length=24),
               comment='StoreStatus: active | suspended | pending_setup.',
               existing_comment='ACTIVE, PAUSED, CLOSED.',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('stores', 'timezone',
               existing_type=sa.VARCHAR(length=64),
               comment='IANA timezone identifier.',
               existing_comment='Store operating timezone.',
               existing_nullable=False,
               existing_server_default=sa.text("'UTC'::character varying"))
    op.alter_column('stores', 'country_code',
               existing_type=sa.CHAR(length=2),
               comment='ISO 3166-1 alpha-2 country code.',
               existing_comment='Primary ISO country code.',
               existing_nullable=False)
    op.alter_column('stores', 'default_currency',
               existing_type=sa.CHAR(length=3),
               comment='ISO 4217 currency code.',
               existing_comment='ISO currency such as INR.',
               existing_nullable=False,
               existing_server_default=sa.text("'USD'::bpchar"))
    op.alter_column('stores', 'legal_name',
               existing_type=sa.VARCHAR(length=200),
               comment='Registered legal business name.',
               existing_comment='Registered business name.',
               existing_nullable=True)
    op.alter_column('stores', 'name',
               existing_type=sa.VARCHAR(length=160),
               comment='Human-readable display name.',
               existing_comment='Merchant/store display name.',
               existing_nullable=False)
    op.alter_column('stores', 'store_id',
               existing_type=sa.UUID(),
               comment='UUID PK generated in Python before INSERT.',
               existing_comment='Primary store identifier.',
               existing_nullable=False)
    op.alter_column('store_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last change.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('store_settings', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Low-risk extensible flags.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('store_settings', 'version',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Optimistic concurrency version for settings edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('store_settings', 'checkout_expiry_minutes',
               existing_type=sa.INTEGER(),
               comment='Minutes before an open checkout session expires.',
               existing_comment='Reservation/checkout lifetime.',
               existing_nullable=False,
               existing_server_default=sa.text('30'))
    op.alter_column('store_settings', 'inventory_policy',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=20),
               comment="'deny' stops sale when OOS; 'continue' allows overselling.",
               existing_comment='Release 1 supports DENY only.',
               existing_nullable=False,
               existing_server_default=sa.text("'DENY'::character varying"))
    op.alter_column('store_settings', 'allow_guest_checkout',
               existing_type=sa.BOOLEAN(),
               comment='Whether shoppers may checkout without an account.',
               existing_comment='Guest checkout switch.',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('store_settings', 'tax_inclusive',
               existing_type=sa.BOOLEAN(),
               comment='Whether product prices include tax.',
               existing_comment='Whether catalog price already contains tax.',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('store_settings', 'dimension_unit',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='cm, in.',
               existing_nullable=False,
               existing_server_default=sa.text("'cm'::character varying"))
    op.alter_column('store_settings', 'weight_unit',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=10),
               comment="Weight unit: 'kg' or 'lb'.",
               existing_comment='kg, g, lb.',
               existing_nullable=False,
               existing_server_default=sa.text("'kg'::character varying"))
    op.alter_column('store_settings', 'order_prefix',
               existing_type=sa.VARCHAR(length=20),
               comment='Prefix for human-readable order numbers.',
               existing_comment='Human order number prefix.',
               existing_nullable=False,
               existing_server_default=sa.text("'ORD'::character varying"))
    op.alter_column('store_settings', 'store_id',
               existing_type=sa.UUID(),
               comment='FK → stores.store_id (1-to-1).',
               existing_comment='One settings row per store.',
               existing_nullable=False)
    op.alter_column('store_settings', 'settings_id',
               existing_type=sa.UUID(),
               comment='UUID PK generated in Python.',
               existing_comment='Settings row id.',
               existing_nullable=False)
    op.drop_constraint('uq_staff_members_store_user', 'staff_members', type_='unique')
    op.create_unique_constraint(op.f('staff_members_user_id_key'), 'staff_members', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_sales_channels_store_name'), 'sales_channels', ['store_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_sales_channels_type'), 'sales_channels', ['channel_type'], unique=False)
    op.alter_column('sales_channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='UTC timestamp of first INSERT (immutable).',
               existing_comment='Created time.',
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sales_channels', 'version',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Optimistic concurrency version for admin edits.',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('sales_channels', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Channel-specific configuration.',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sales_channels', 'status',
               existing_type=sa.VARCHAR(length=24),
               comment=None,
               existing_comment='ACTIVE/INACTIVE.',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::character varying"))
    op.alter_column('sales_channels', 'channel_type',
               existing_type=sa.VARCHAR(length=32),
               comment="Channel type: 'online_store' | 'pos' | 'api'.",
               existing_comment='STOREFRONT, ADMIN, MARKETPLACE, POS, API.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment='Human-readable channel label.',
               existing_comment='Online Store, Admin Draft, Instagram, etc.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'store_id',
               existing_type=sa.UUID(),
               comment='FK → stores.store_id.',
               existing_comment='Owning store.',
               existing_nullable=False)
    op.alter_column('sales_channels', 'channel_id',
               existing_type=sa.UUID(),
               comment='UUID PK generated in Python.',
               existing_comment='Channel id.',
               existing_nullable=False)
    op.drop_constraint('uq_refresh_tokens_hash', 'refresh_tokens', type_='unique')
    op.create_unique_constraint(op.f('refresh_tokens_token_hash_key'), 'refresh_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_permissions_code', 'permissions', type_='unique')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.alter_column('permissions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.add_column('customers', sa.Column('tags', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('version', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False))
    op.add_column('customer_notes', sa.Column('created_by_staff_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('customer_notes', sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('customer_notes_store_id_fkey'), 'customer_notes', 'stores', ['store_id'], ['store_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
