"""initial_schema_v3

Revision ID: d7c72d34a266
Revises: 
Create Date: 2026-09-15 15:58:47.579556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7c72d34a266'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_table('stores',
    sa.Column('store_id', sa.UUID(), nullable=False, comment='UUID PK generated in Python before INSERT.'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Human-readable display name.'),
    sa.Column('slug', sa.String(length=80), nullable=False, comment='URL-friendly unique identifier.'),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Registered legal business name.'),
    sa.Column('email', postgresql.CITEXT(), nullable=False, comment='Primary contact e-mail — CITEXT for case-insensitive storage.'),
    sa.Column('phone', sa.String(length=32), nullable=True, comment='Optional phone number in E.164 format.'),
    sa.Column('country_code', sa.CHAR(length=2), nullable=False, comment='ISO 3166-1 alpha-2 country code.'),
    sa.Column('currency', sa.CHAR(length=3), server_default='USD', nullable=False, comment='ISO 4217 currency code.'),
    sa.Column('timezone', sa.String(length=60), server_default='UTC', nullable=False, comment='IANA timezone identifier.'),
    sa.Column('status', sa.String(length=24), server_default='pending_setup', nullable=False, comment='StoreStatus: active | suspended | pending_setup.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_table('customers',
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('accepts_marketing', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_spent', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('orders_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_order_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.BigInteger(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index('ix_customers_store_email', 'customers', ['store_id', 'email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index(op.f('ix_customers_store_id'), 'customers', ['store_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('store_id', 'name', name='uq_roles_store_name')
    )
    op.create_index(op.f('ix_roles_store_id'), 'roles', ['store_id'], unique=False)
    op.create_table('sales_channels',
    sa.Column('channel_id', sa.UUID(), nullable=False, comment='UUID PK generated in Python.'),
    sa.Column('store_id', sa.UUID(), nullable=False, comment='FK → stores.store_id.'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable channel label.'),
    sa.Column('channel_type', sa.String(length=30), nullable=False, comment="Channel type: 'online_store' | 'pos' | 'api'."),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this channel is currently enabled.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp of first INSERT (immutable).'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_index(op.f('ix_sales_channels_store_id'), 'sales_channels', ['store_id'], unique=False)
    op.create_table('store_settings',
    sa.Column('setting_id', sa.UUID(), nullable=False, comment='UUID PK generated in Python.'),
    sa.Column('store_id', sa.UUID(), nullable=False, comment='FK → stores.store_id (1-to-1).'),
    sa.Column('order_prefix', sa.String(length=20), server_default='ORD-', nullable=False, comment='Prefix for human-readable order numbers.'),
    sa.Column('weight_unit', sa.String(length=10), server_default='kg', nullable=False, comment="Weight unit: 'kg' or 'lb'."),
    sa.Column('tax_inclusive', sa.Boolean(), server_default='false', nullable=False, comment='Whether product prices include tax.'),
    sa.Column('allow_guest_checkout', sa.Boolean(), server_default='true', nullable=False, comment='Whether shoppers may checkout without an account.'),
    sa.Column('inventory_policy', sa.String(length=20), server_default='deny', nullable=False, comment="'deny' stops sale when OOS; 'continue' allows overselling."),
    sa.Column('checkout_expiry_minutes', sa.Integer(), server_default='30', nullable=False, comment='Minutes before an open checkout session expires.'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('setting_id'),
    sa.UniqueConstraint('store_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('store_id', 'email', name='uq_users_store_email')
    )
    op.create_index(op.f('ix_users_store_id'), 'users', ['store_id'], unique=False)
    op.create_table('customer_addresses',
    sa.Column('address_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address_id')
    )
    op.create_index(op.f('ix_customer_addresses_customer_id'), 'customer_addresses', ['customer_id'], unique=False)
    op.create_table('customer_consents',
    sa.Column('consent_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consent_id'),
    sa.UniqueConstraint('customer_id', 'consent_type', name='uq_customer_consents')
    )
    op.create_index(op.f('ix_customer_consents_customer_id'), 'customer_consents', ['customer_id'], unique=False)
    op.create_table('customer_notes',
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_by_staff_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_customer_notes_customer_id'), 'customer_notes', ['customer_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('staff_members',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.store_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_member_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_members_store_id'), 'staff_members', ['store_id'], unique=False)
    op.create_table('staff_member_roles',
    sa.Column('staff_member_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_member_id'], ['staff_members.staff_member_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_member_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_member_roles')
    op.drop_index(op.f('ix_staff_members_store_id'), table_name='staff_members')
    op.drop_table('staff_members')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_customer_notes_customer_id'), table_name='customer_notes')
    op.drop_table('customer_notes')
    op.drop_index(op.f('ix_customer_consents_customer_id'), table_name='customer_consents')
    op.drop_table('customer_consents')
    op.drop_index(op.f('ix_customer_addresses_customer_id'), table_name='customer_addresses')
    op.drop_table('customer_addresses')
    op.drop_index(op.f('ix_users_store_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('store_settings')
    op.drop_index(op.f('ix_sales_channels_store_id'), table_name='sales_channels')
    op.drop_table('sales_channels')
    op.drop_index(op.f('ix_roles_store_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_customers_store_id'), table_name='customers')
    op.drop_index('ix_customers_store_email', table_name='customers', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_table('customers')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
