from __future__ import annotations

from typing import Protocol
from uuid import UUID

from modules.catalog.infrastructure.db.models import (
    CollectionModel,
    CollectionProductModel,
    MediaAssetModel,
    MetafieldDefinitionModel,
    MetafieldModel,
    ProductMediaModel,
    ProductModel,
    ProductOptionModel,
    ProductOptionValueModel,
    ProductTagModel,
    ProductVariantModel,
    TagModel,
    VariantOptionValueModel,
)


class ICatalogRepository(Protocol):
    """Abstract repository port interface for catalog entities."""

    async def create_product(self, product: ProductModel) -> ProductModel: ...
    async def get_product(self, store_id: UUID, product_id: UUID) -> ProductModel | None: ...
    async def get_product_by_slug(self, store_id: UUID, slug: str) -> ProductModel | None: ...
    async def list_products(self, store_id: UUID, status: str | None = None) -> list[ProductModel]: ...
    async def update_product(self, store_id: UUID, product_id: UUID, values: dict) -> ProductModel | None: ...
    async def delete_product(self, store_id: UUID, product_id: UUID) -> bool: ...

    async def create_option(self, option: ProductOptionModel) -> ProductOptionModel: ...
    async def get_option(self, product_id: UUID, option_id: UUID) -> ProductOptionModel | None: ...
    async def list_options(self, product_id: UUID) -> list[ProductOptionModel]: ...
    async def update_option(self, product_id: UUID, option_id: UUID, values: dict) -> ProductOptionModel | None: ...

    async def create_option_value(self, option_value: ProductOptionValueModel) -> ProductOptionValueModel: ...
    async def list_option_values(self, option_id: UUID) -> list[ProductOptionValueModel]: ...

    async def create_variant(self, variant: ProductVariantModel) -> ProductVariantModel: ...
    async def get_variant(self, store_id: UUID, variant_id: UUID) -> ProductVariantModel | None: ...
    async def get_variant_by_sku(self, store_id: UUID, sku: str) -> ProductVariantModel | None: ...
    async def get_variant_by_signature(self, product_id: UUID, option_signature: str) -> ProductVariantModel | None: ...
    async def list_variants(self, product_id: UUID) -> list[ProductVariantModel]: ...
    async def update_variant(self, store_id: UUID, variant_id: UUID, values: dict) -> ProductVariantModel | None: ...

    async def add_variant_option_value(self, item: VariantOptionValueModel) -> VariantOptionValueModel: ...
    async def list_variant_option_values(self, variant_id: UUID) -> list[VariantOptionValueModel]: ...

    async def create_media(self, media: MediaAssetModel) -> MediaAssetModel: ...
    async def get_media(self, store_id: UUID, media_id: UUID) -> MediaAssetModel | None: ...
    async def update_media(self, store_id: UUID, media_id: UUID, values: dict) -> MediaAssetModel | None: ...

    async def add_product_media(self, item: ProductMediaModel) -> ProductMediaModel: ...
    async def get_product_media(self, product_id: UUID) -> list[ProductMediaModel]: ...
    async def delete_product_media(self, product_id: UUID) -> None: ...

    async def create_collection(self, collection: CollectionModel) -> CollectionModel: ...
    async def get_collection(self, store_id: UUID, collection_id: UUID) -> CollectionModel | None: ...
    async def get_collection_by_slug(self, store_id: UUID, slug: str) -> CollectionModel | None: ...
    async def list_collections(self, store_id: UUID, status: str | None = None) -> list[CollectionModel]: ...
    async def update_collection(self, store_id: UUID, collection_id: UUID, values: dict) -> CollectionModel | None: ...

    async def add_collection_product(self, item: CollectionProductModel) -> CollectionProductModel: ...
    async def get_collection_products(self, collection_id: UUID) -> list[CollectionProductModel]: ...
    async def delete_collection_products(self, collection_id: UUID) -> None: ...

    async def get_tag(self, store_id: UUID, name: str) -> TagModel | None: ...
    async def create_tag(self, tag: TagModel) -> TagModel: ...
    async def get_product_tags(self, product_id: UUID) -> list[ProductTagModel]: ...
    async def delete_product_tags(self, product_id: UUID) -> None: ...
    async def add_product_tag(self, item: ProductTagModel) -> ProductTagModel: ...

    async def create_metafield_definition(self, definition: MetafieldDefinitionModel) -> MetafieldDefinitionModel: ...
    async def get_metafield_definition(self, store_id: UUID, definition_id: UUID) -> MetafieldDefinitionModel | None: ...
    async def list_metafield_definitions(self, store_id: UUID, resource_type: str | None = None) -> list[MetafieldDefinitionModel]: ...

    async def create_metafield(self, metafield: MetafieldModel) -> MetafieldModel: ...
    async def get_metafield(self, definition_id: UUID, resource_id: UUID) -> MetafieldModel | None: ...
    async def update_metafield(self, definition_id: UUID, resource_id: UUID, values: dict) -> MetafieldModel | None: ...
